import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';

const Meta = () => {
  return (
    <Head>
      <title>Create Gluestack App</title>
      <meta name="description" content="Generated by node glue add web" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

const FeatureCard = ({ iconSvg, name, desc }: any) => {
  return (
    <div className={styles.card}>
      <div>
        <Image
          src={`/${iconSvg}`}
          alt="document"
          width={22}
          height={22}
          priority
        />
        <h3>{name}</h3>
      </div>
      <p>{desc}</p>
    </div>
  );
};

const Example = () => {
  return (
    <>
      <button onClick={console.log('Hello World')}>Hello</button>
    </>
  );
};

const Home: NextPage = () => {
  return (
    <div className={styles.parent}>
      <Example />
    </div>
  );
};

export default Home;
